# FastAPI - Dev 환경

replicaCount: 1

image:
  tag: "latest"  # CI가 commit sha로 업데이트

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: false

pdb:
  enabled: false

env:
  - name: ENV
    value: "dev"
