# FastAPI - Prod 환경

replicaCount: 2

image:
  tag: "latest"  # CI가 commit sha로 업데이트

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 50
  scaleDownStabilization: 300

pdb:
  enabled: true
  minAvailable: "50%"

env: []

envFromSecret:
  - name: ENV
    secretName: fastapi-secret
    key: env
  - name: QDRANT_URL
    secretName: fastapi-secret
    key: qdrant-url
  - name: QDRANT_API_KEY
    secretName: fastapi-secret
    key: qdrant-api-key
  - name: DB_URL
    secretName: fastapi-secret
    key: db-url
