# village-app: Default Deny All
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: village-app
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# village-data: Default Deny All
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: village-data
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
