replicaCount: 2

image:
  repository: "988319239270.dkr.ecr.ap-northeast-2.amazonaws.com/billage-fe"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

strategy:
  maxSurge: "25%"
  maxUnavailable: 0

probes:
  readiness:
    path: /login
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    path: /login
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 3

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPU: 70
  scaleDownStabilization: 300

pdb:
  enabled: true
  minAvailable: "50%"

env: []
