apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: billage-apps
  namespace: billage-ops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - chart: spring-boot
            service: api
            targetNamespace: billage-app
          - chart: nextjs
            service: web
            targetNamespace: billage-app
          - chart: fastapi
            service: ai
            targetNamespace: billage-app

  template:
    metadata:
      name: 'billage-{{.service}}-prod'
      namespace: billage-ops
      labels:
        app.kubernetes.io/part-of: billage
        environment: prod
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: billage
      source:
        repoURL: 'https://github.com/kimyuchan-k1/billage-k8s.git'
        targetRevision: main
        path: 'charts/{{.chart}}'
        helm:
          valueFiles:
            - 'values.yaml'
            - 'values-prod.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.targetNamespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=false
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 5
